project_name: prometheus-cve-exporter
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/prometheus-cve-exporter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/zadjadr/prometheus-cve-exporter:{{ .Tag }}"
      - "ghcr.io/zadjadr/prometheus-cve-exporter:v{{ .Major }}"
      - "ghcr.io/zadjadr/prometheus-cve-exporter:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/zadjadr/prometheus-cve-exporter:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Prometheus CVE Exporter is a Golang application that scans your system for all installed packages and compares them with the recent NVD JSON feed. It exports metrics that provide insights into the security status of your packages."
      - --label=org.opencontainers.image.url=https://github.com/zadjadr/prometheus-cve-exporter
      - --label=org.opencontainers.image.source=https://github.com/zadjadr/prometheus-cve-exporter
      - --label=org.opencontainers.image.version=v{{ .Major }}.{{ .Minor }}"
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
nfpms:
  - maintainer: Zadjad Rezai <me@zops.top>
    description: Prometheus CVE Exporter is a Golang application that scans your system for all installed packages and compares them with the recent NVD JSON feed. It exports metrics that provide insights into the security status of your packages.
    homepage: https://github.com/zadjadr/prometheus-cve-exporter
    license: MIT
    formats:
      - deb
      - rpm
      - apk
