name: Release

on:
  create:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -v -o ./bin/ ./...

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
            ./bin/prometheus-cve-exporter

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-cve-exporter
          path: ./bin/prometheus-cve-exporter
