name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  create:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -v -o ./bin/ ./...

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
            LICENSE
            ./bin/prometheus-cve-exporter

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-cve-exporter
          path: ./bin/prometheus-cve-exporter
